language: node_js
node_js:
  - "6"

cache:
  directories:
    - sysconfcpus
    - $(npm config get prefix)/lib/node_modules
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts

env:
  - ELM_VERSION=0.18.0

install:
  - node --version
  - npm --version
  - npm install -g elm elm-test uglify-es uglifycss
  - mkdir out

script:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git; 
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make src/Main.elm --output=static/elm.js --yes
  -  uglifyjs static/script.js static/chartist.min.js static/elm.js static/loadCSS.min.js > out/bundle.js
  - uglifycss static/style.css static/chartist.min.css > out/bundle.css
  - cp static/logo.png static/favicon.ico static/CNAME static/index.html out/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out 
  fqdn: growing.cash
  on:
    branch: master 
