language: node_js
node_js:
  - "6"

cache:
  directories:
    - sysconfcpus

env:
  - ELM_VERSION=0.18.0

install:
  - node --version
  - npm --version
  - npm install -g elm
  - mkdir out

script:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git; 
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make src/Main.elm --output=output/index.html --yes
  - cp src/style.css output/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  on:
    branch: master 
