language: node_js
node_js:
  - "6"

cache:
  directories:
    - sysconfcpus

env:
  - ELM_VERSION=0.18.0

install:
  - node --version
  - npm --version
  - npm install -g elm google-closure-compiler-js elm-static-html
  - mkdir out

script:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git; 
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make src/Main.elm --output=static/elm.js --yes
  - google-closure-compiler-js static/elm.js > out/elm.js
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-static-html -f src/InitialView.elm -o static/main.html
  - cat static/intro.html static/main.html static/outro.html > out/index.html
  - cp static/CNAME static/style.css out/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out 
  fqdn: growing.cash
  on:
    branch: master 
