language: node_js
node_js:
  - "6"

cache:
  directories:
    - sysconfcpus
    - $(npm config get prefix)/lib/node_modules
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts

env:
  - ELM_VERSION=0.18.0

install:
  - node --version
  - npm --version
  - npm install -g elm elm-test
  - mkdir out

script:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git; 
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-test
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make src/Main.elm --output=out/elm.js --yes
  - cat static/intro.html static/style.css static/outro.html > out/index.html
  - cp static/chartist.min.js static/chartist.min.css static/logo.png static/favicon.ico static/CNAME out/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: out 
  fqdn: growing.cash
  on:
    branch: master 
